version: '3.8'

services:
  # ==========================================
  # FRONTEND - NEXT.JS (PRODUÇÃO)
  # ==========================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NODE_ENV: production
    container_name: iast-frontend-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:4000}
      - PORT=3001
    restart: always
    networks:
      - iast-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================
  # BACKEND - NODE.JS + EXPRESS (PRODUÇÃO)
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: iast-backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src/corpus:/app/corpus:ro
      - backend-uploads-prod:/app/uploads
    restart: always
    networks:
      - iast-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ==========================================
# VOLUMES NOMEADOS (PRODUÇÃO)
# ==========================================
volumes:
  backend-uploads-prod:
    driver: local

# ==========================================
# REDE CUSTOMIZADA
# ==========================================
networks:
  iast-network:
    driver: bridge

